title:              "Inside The Source Code"
description:        "Inside The Source Code Blog"
disqus_shortname:   insidethesourcecode
share:              true
dropcap:            true
readtime:           true
url:                http://tswiackiewicz.github.io/inside-the-source-code

# owner/author information
owner:
  name:             "Tomasz Świacko-Świackiewicz"
  avatar:           avatar.png
  email:
  description:      "Software Architect, GetResponse"
  linkedin:         https://pl.linkedin.com/in/tomasz-%C5%9Bwiacko-%C5%9Bwiackiewicz-9b8029114
  github:           tswiackiewicz

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-61454272-1
google_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: "Strona główna"
    url: /
  - title: "Archiwum"
    url: /archive
  - title: "Kategorie"
    url: /categories
  - title: "Tagi"
    url: /tags
  - title: "O mnie"
    url: /about

timezone:       UTC
future:         true
markdown:       kramdown
highlighter:    rouge
paginate:       5

permalink:      /:categories/:title/

kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  input:            GFM
  syntax_highlighter: rouge

plugins: ["jekyll-paginate"]
include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
